---
title: "TD metabolome"
author: "Delpierot AUGUSTIN"
date: "24/01/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MultiVarSel)
library(reshape)
library(ggplot2)
```

##Lecture des données

```{r}
table1=read.table("metabolomeAth.csv", sep=";", header=T, dec=",")
table1[1:3,1:10]
```
```{r}
dim(table1)
```

```{r}
table1[,1]
```

```{r}
table=table1[,-1]
table[1:3,1:5]
```
```{r}
#### Creation d'une variable qualitative supplementaire pour enlever les noms des replicats
temperature<-rep(c("FROID", "STD", "CHAUD"), each=3)
table2<-data.frame(temperature,table) # nouveau tableau
table2[1:9,1:10]
```
```{r}
which(colMeans(table2[,2:dim(table2)[2]])==0)
```

```{r}
#Permet de voir s'il y a une colonne dont la valeur ne change jamais
#table2[,2 :à parir de la 2ème colonne
#(table2)[2] : On ne s'interesse qu'aux colonnes
#conseils préparations : commencer par une analyse decriptive (boxplot, ACP)
which(apply(table2[,2:dim(table2)[2]],2,sd)==0)
```

```{r}
which(is.na(table2))
```

##Matrices Y et X

```{r}
#On enlève la colonne des noms juste pour avoir unique des reponse
Y <- as.matrix(table2[, -1])

#On envie envie d'estimer toute les variables, on ne met donc pas de contraintes
#+0
X <- model.matrix(lm(Y ~ temperature + 0,data=table2))
p <- ncol(X)
n=nrow(X)
print(n)
```

```{r}
q=dim(Y)[2]
print(q)
```

```{r}
#On centre nos valeurs permet de ne pas donner plus d'importance à une variable qu'une autre
Y=scale(Y)
```

```{r}
#On fait une ANOVA à un facteur colonne par colonnes
#On espère garder la structure de dépendance
residus=lm(as.matrix(Y)~X-1)$residuals
```


```{r}
#on cherche de savoir s'il y a de la dependance entre les colonness : test de blancheurs
pvalue=whitening_test(residus)
print(pvalue)
```

```{r}
#Permet d'identifier la structure de dépendance
#On fait le test de blancheur en regardant si l'on applique différents types de structures
#Permet de trpiver la modélisation de la dépendance la plus addaptée pour estimer sigma
#Plus la p-value est élevée, plus c'est mieux
#Dans notre cas nous comparons un modèle ARMA à une structure en Toplitz
whitening_choice(residus, typeDeps = c("AR1","nonparam"), pAR = 1, qMA = 0)
```
```{r}
#Correspond à la transformation des données selon le sytème
square_root_inv_hat_Sigma=whitening(residus,"nonparam",pAR=1,qMA=0)
```

```{r}
Freqs=variable_selection(Y,X,square_root_inv_hat_Sigma,nb_repli=5,parallel=FALSE,nb.cores=2)

#Quel coef est pertinent?
Freqs
```

```{r}
#Renommer les colonnes freqs
colnames(Freqs)<-c('Names_of_Y','Names_of_X','frequency')

```

```{r}
plot(sort(Freqs$frequency,decreasing = T),type='s')
sort(Freqs$frequency,decreasing = T)[1:50]
```

```{r}
seuil=0.93
Freqs$Names_of_X=gsub(pattern='temperature',replacement='',Freqs$Names_of_X)
indices=which(Freqs$frequency>=seuil)
```

```{r}
Yvec=as.numeric(Y%*%square_root_inv_hat_Sigma)
Xvec=kronecker(t(square_root_inv_hat_Sigma),X)
Xvec_sel=Xvec[,indices]
B_sel_hat=solve(t(Xvec_sel)%*%Xvec_sel,t(Xvec_sel)%*%Yvec)
Freqs$estim=rep(0,p*q)
Freqs$estim[indices]=as.vector(B_sel_hat)
library(ggplot2)
gr<-ggplot(data=Freqs[Freqs$frequency>=seuil,],
aes(x=Names_of_Y,y=Names_of_X,color=estim))+
scale_color_gradient2(low="steelblue",mid = "white", high ="red")+
geom_point(size=2)+theme_bw()+
ylab('Température')+
xlab('Métabolites')+theme(axis.text.x = element_text(angle=90))
gr
```

```{r}

```

